name: go-sharedstore

up:
  - go:
      version: "1.16.7"
      modules: true
  - custom:
        name: Load dependencies
        met?: go mod tidy
        meet: go mod tidy

commands:
  test: go test -race ./...
  style:
    run: bin/style
    desc: Static verification using golangci or autofix issues when possible.
    syntax:
      optional: --fix
